import {useEffect,useId,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Field,Icon,Upload} from './shared.jsx';
import {validateContent,iconNames} from '../src/content-schema.js';
import {copyGroups,sectionLabels} from './editor-fields.js';

const tabs=[['resumen','Tu página','home'],['inicio','Portada','photo'],['movimiento','El movimiento','community'],['plan','Plan de trabajo','document'],['equipo','El equipo','profile'],['parroquia','La parroquia','map-pin'],['contacto','Contacto y redes','mail'],['preguntas','Preguntas frecuentes','info-circle'],['ajustes','Marca y estructura','settings']];
const iconLabels={road:'Vías',leaf:'Producción y naturaleza',community:'Comunidad',shield:'Seguridad',droplet:'Agua',document:'Documento',landscape:'Territorio',profile:'Persona','map-pin':'Ubicación'};
const serialize=content=>JSON.stringify(content);
function Switch({label,checked,onChange,hint}) {const id=useId();return <div className="cms-switch-row"><div><label htmlFor={id}>{label}</label>{hint&&<p>{hint}</p>}</div><input id={id} type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/></div>;}
function CopyEditor({section,data,update}) {return <div className="cms-fields">{(copyGroups[section]||[]).map(([key,label])=><Field key={key} label={label} value={data.copy[key]} multiline={data.copy[key]?.includes('\n')||data.copy[key]?.length>110||/Description|Lead|Body|Note|Text|Privacy|Footnote/i.test(key)} onChange={value=>update(['copy',key],value)}/>)}</div>;}
function Editor({tab,data,update,csrf,setTab}) {
  const move=(collection,index,delta)=>{const items=[...data[collection]],next=index+delta;if(next<0||next>=items.length)return;[items[index],items[next]]=[items[next],items[index]];update([collection],items);};
  if(tab==='resumen')return <div className="cms-overview"><h1>Tu página, en orden.</h1><p>Edita una sección, revisa el borrador y aplica los cambios cuando esté listo.</p><div className="cms-section-list">{tabs.slice(1).map(([id,label,icon])=><button key={id} onClick={()=>setTab(id)}><Icon name={icon}/><span><strong>{label}</strong><small>{id==='equipo'?'Los cuatro integrantes, fotografías y perfiles':id==='parroquia'?'Fotografías de Octavio Cordero Palacios':id==='plan'?'Seis temas, propuestas y documento completo':id==='ajustes'?'Identidad, menú, visibilidad y orden':'Textos y contenido de esta sección'}</small></span><Icon name="arrow-up-right"/></button>)}</div><div className="cms-local-note"><Icon name="info-circle"/><p>Estás editando el sitio en este equipo. El acceso privado desde celular se conectará cuando publiquemos la página.</p></div></div>;
  return <>
    <div className="editor-title"><Icon name={tabs.find(entry=>entry[0]===tab)?.[2]}/><div><h1>{tabs.find(entry=>entry[0]===tab)?.[1]}</h1><p>Los cambios se conservan al navegar entre secciones del panel.</p></div></div>
    {tab==='inicio'&&<section className="cms-block"><h2>Arte principal</h2><div className="cms-art-preview"><img src={data.brand.wordmark} alt="Arte actual de la portada"/></div><Upload csrf={csrf} label="Reemplazar arte de la portada" onUploaded={value=>update(['brand','wordmark'],value)}/><Field label="Frase accesible de la portada" value={data.brand.slogan} onChange={value=>update(['brand','slogan'],value)} hint="El texto impreso dentro del arte se cambia reemplazando la imagen."/></section>}
    <section className="cms-block"><h2>{tab==='ajustes'?'Vista previa y pie de página':'Textos de la sección'}</h2><CopyEditor section={tab} data={data} update={update}/></section>
    {tab==='equipo'&&data.members.map((member,index)=><section className="cms-block" key={index}><h2>{member.name||`Integrante ${index+1}`}</h2><div className="cms-media-row"><div className="cms-person-preview">{member.photo?<img src={member.photo} alt={member.name}/>:<Icon name="profile"/>}</div><div><Upload csrf={csrf} onUploaded={value=>update(['members',index,'photo'],value)}/>{member.photo&&<button className="cms-button quiet" onClick={()=>update(['members',index,'photo'],'')}>Quitar fotografía</button>}</div></div><div className="cms-two-columns"><Field label="Nombre completo" value={member.name} onChange={value=>update(['members',index,'name'],value)} required/><Field label="Rol" value={member.role} onChange={value=>update(['members',index,'role'],value)} required/></div><Field label="Trayectoria y presentación" value={member.bio} multiline onChange={value=>update(['members',index,'bio'],value)}/></section>)}
    {tab==='plan'&&<><section className="cms-block"><h2>Documento completo</h2><Field label="Enlace al documento" value={data.officialPlanUrl} onChange={value=>update(['officialPlanUrl'],value)} hint="Puedes conservar el lector actual o reemplazarlo por un PDF."/><Field label="Texto del botón" value={data.planDownloadLabel} onChange={value=>update(['planDownloadLabel'],value)}/><Upload csrf={csrf} kind="document" label="Subir un PDF del plan" onUploaded={value=>update(['officialPlanUrl'],value)}/></section>{data.plan.map((plan,index)=><section className="cms-block" key={plan.id}><h2>{plan.title}</h2><Field label="Nombre del tema" value={plan.title} onChange={value=>update(['plan',index,'title'],value)}/><div className="cms-field"><label htmlFor={`plan-icon-${index}`}>Icono del tema</label><select id={`plan-icon-${index}`} value={plan.icon} onChange={event=>update(['plan',index,'icon'],event.target.value)}>{iconNames.map(icon=><option key={icon} value={icon}>{iconLabels[icon]}</option>)}</select></div><Field label="Introducción del tema" value={plan.description} multiline onChange={value=>update(['plan',index,'description'],value)}/>{plan.items.map((item,itemIndex)=><div className="cms-repeat-row" key={itemIndex}><div className="repeat-heading"><strong>Propuesta {itemIndex+1}</strong><button className="cms-button quiet" disabled={plan.items.length===1} onClick={()=>update(['plan',index,'items'],plan.items.filter((_,i)=>i!==itemIndex))}><Icon name="trash"/>Quitar</button></div><Field label="Título de la propuesta" value={item.title} onChange={value=>update(['plan',index,'items',itemIndex,'title'],value)}/><Field label="Acciones y detalles" value={item.text} multiline onChange={value=>update(['plan',index,'items',itemIndex,'text'],value)}/></div>)}<button className="cms-button secondary" disabled={plan.items.length>=30} onClick={()=>update(['plan',index,'items'],[...plan.items,{title:'',text:''}])}><Icon name="plus"/>Añadir propuesta</button></section>)}</>}
    {tab==='parroquia'&&<><div className="cms-local-note"><Icon name="map-pin"/><p>Utiliza exclusivamente fotografías tomadas en Octavio Cordero Palacios. Completa la descripción, autoría y permiso de uso.</p></div>{data.photos.map((photo,index)=><section className="cms-block" key={index}><div className="repeat-heading"><h2>{photo.title||`Fotografía ${index+1}`}</h2><div className="row-actions"><button aria-label={`Subir fotografía ${index+1} en el orden`} disabled={index===0} onClick={()=>move('photos',index,-1)}><Icon name="arrow-up"/></button><button aria-label={`Bajar fotografía ${index+1} en el orden`} disabled={index===data.photos.length-1} onClick={()=>move('photos',index,1)}><Icon name="arrow-down"/></button><button aria-label={`Quitar fotografía ${index+1}`} disabled={data.photos.length===1} onClick={()=>update(['photos'],data.photos.filter((_,i)=>i!==index))}><Icon name="trash"/></button></div></div>{photo.src&&<img className="cms-photo-preview" src={photo.src} alt={photo.alt||'Fotografía por describir'}/>}<Upload csrf={csrf} onUploaded={value=>update(['photos',index,'src'],value)}/><Switch label="La fotografía fue tomada en Octavio Cordero Palacios" checked={photo.location==='Octavio Cordero Palacios'} onChange={checked=>update(['photos',index,'location'],checked?'Octavio Cordero Palacios':'')}/><div className="cms-two-columns"><Field label="Título" value={photo.title} onChange={value=>update(['photos',index,'title'],value)}/><Field label="Pie de foto" value={photo.caption} onChange={value=>update(['photos',index,'caption'],value)}/></div><Field label="Descripción para accesibilidad" value={photo.alt} onChange={value=>update(['photos',index,'alt'],value)}/><div className="cms-two-columns"><Field label="Autor o autora" value={photo.author} onChange={value=>update(['photos',index,'author'],value)}/><Field label="Licencia o permiso" value={photo.license} onChange={value=>update(['photos',index,'license'],value)}/></div><Field label="Enlace de la fuente" value={photo.source} onChange={value=>update(['photos',index,'source'],value)}/><Field label="Enlace de la licencia" value={photo.licenseUrl} onChange={value=>update(['photos',index,'licenseUrl'],value)}/><Field label="Notas de crédito" value={photo.creditNote} multiline onChange={value=>update(['photos',index,'creditNote'],value)}/></section>)}<button className="cms-button secondary" disabled={data.photos.length>=12} onClick={()=>update(['photos'],[...data.photos,{src:'',title:'',caption:'',alt:'',author:'',source:'',license:'',licenseUrl:'',creditNote:'',location:''}])}><Icon name="plus"/>Añadir fotografía</button></>}
    {tab==='contacto'&&<section className="cms-block"><h2>Canales oficiales</h2><p className="block-description">Deja vacío cualquier canal que todavía no exista.</p>{[['email','Correo electrónico'],['phone','Teléfono'],['whatsapp','WhatsApp: código de país y número'],['facebook','Enlace de Facebook'],['instagram','Enlace de Instagram'],['tiktok','Enlace de TikTok']].map(([key,label])=><Field key={key} label={label} value={data.contact[key]} onChange={value=>update(['contact',key],value)} hint={['facebook','instagram','tiktok'].includes(key)?'Usa el enlace HTTPS de la cuenta oficial.':undefined}/>)}</section>}
    {tab==='preguntas'&&<>{data.faqs.map((faq,index)=><section className="cms-block" key={index}><div className="repeat-heading"><h2>Pregunta {index+1}</h2><button className="cms-button quiet" onClick={()=>update(['faqs'],data.faqs.filter((_,i)=>i!==index))}><Icon name="trash"/>Quitar</button></div><Field label="Pregunta" value={faq.question} onChange={value=>update(['faqs',index,'question'],value)}/><Field label="Respuesta" value={faq.answer} multiline onChange={value=>update(['faqs',index,'answer'],value)}/></section>)}<button className="cms-button secondary" disabled={data.faqs.length>=30} onClick={()=>update(['faqs'],[...data.faqs,{question:'',answer:''}])}><Icon name="plus"/>Añadir pregunta</button></>}
    {tab==='ajustes'&&<><section className="cms-block"><h2>Identidad</h2><div className="cms-two-columns"><Field label="Nombre del movimiento" value={data.brand.name} onChange={value=>update(['brand','name'],value)}/><Field label="Número" value={data.brand.number} onChange={value=>update(['brand','number'],value)}/></div><Field label="Texto de la marca en el menú" value={data.brand.label} multiline onChange={value=>update(['brand','label'],value)}/><Field label="Color principal" value={data.brand.accent} type="color" onChange={value=>update(['brand','accent'],value)} hint="El naranja de campaña es #ff5d15. Se aplica como acento."/><Switch label="Mostrar avisos de contenido en preparación" checked={data.preview} onChange={value=>update(['preview'],value)}/></section><section className="cms-block"><h2>Menú</h2>{data.navigation.map((item,index)=><Field key={item.id} label={sectionLabels[item.id]} value={item.label} onChange={value=>update(['navigation',index,'label'],value)}/>)}</section><section className="cms-block"><h2>Orden y visibilidad</h2>{data.sections.map((section,index)=><div className="section-order-row" key={section.id}><Switch label={sectionLabels[section.id]} checked={section.enabled} onChange={value=>update(['sections',index,'enabled'],value)}/><div className="row-actions"><button aria-label={`Subir ${sectionLabels[section.id]}`} disabled={index===0} onClick={()=>move('sections',index,-1)}><Icon name="arrow-up"/></button><button aria-label={`Bajar ${sectionLabels[section.id]}`} disabled={index===data.sections.length-1} onClick={()=>move('sections',index,1)}><Icon name="arrow-down"/></button></div></div>)}</section><section className="cms-block"><h2>Título y descripción del sitio</h2><Field label="Título de la pestaña" value={data.seo.title} onChange={value=>update(['seo','title'],value)}/><Field label="Descripción" value={data.seo.description} multiline onChange={value=>update(['seo','description'],value)}/></section></>}
  </>;
}
function CMS() {
  const [state,setState]=useState(null),[data,setData]=useState(null),[baseline,setBaseline]=useState(''),[tab,setTab]=useState('resumen'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[errors,setErrors]=useState([]),[loadError,setLoadError]=useState(''),[preview,setPreview]=useState(false),[previewKey,setPreviewKey]=useState(0),[menu,setMenu]=useState(false),[discard,setDiscard]=useState(false);
  const importRef=useRef(null);const dirty=data&&serialize(data)!==baseline;
  const selectTab=id=>{setTab(id);setMenu(false);setMessage('');setErrors([]);window.scrollTo({top:0,behavior:'instant'});};
  async function load() {setLoadError('');try{const response=await fetch('/api/cms/state',{cache:'no-store'});if(!response.ok)throw new Error('El panel necesita el servidor local del proyecto. Inícialo con el acceso de desarrollo.');const result=await response.json();setState(result);setData(result.draft);setBaseline(serialize(result.draft));setErrors([]);setDiscard(false);}catch(error){setLoadError(error.message);}}
  useEffect(()=>{load();},[]);
  useEffect(()=>{const warn=event=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const update=(path,value)=>{setData(previous=>{const next=structuredClone(previous);let entry=next;for(const key of path.slice(0,-1))entry=entry[key];entry[path.at(-1)]=value;return next;});setMessage('');setErrors([]);};
  async function save(publish=false) {
    const issues=validateContent(data);if(issues.length){setErrors(issues);setMessage('Revisa los campos señalados antes de guardar.');return false;}
    setBusy(true);setErrors([]);
    try {const response=await fetch(publish?'/api/cms/publish':'/api/cms/draft',{method:publish?'POST':'PUT',headers:{'Content-Type':'application/json','X-CMS-Token':state.csrfToken},body:JSON.stringify({content:data,revision:state.revision,draftRevision:state.draftRevision})});const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo guardar.');setState(result);setData(result.draft);setBaseline(serialize(result.draft));setMessage(publish?'Cambios aplicados al sitio local. La versión anterior tiene una copia de respaldo.':'Borrador guardado. La página principal conserva su versión anterior.');setPreviewKey(Date.now());return true;}catch(error){setErrors([error.message]);return false;}finally{setBusy(false);}
  }
  async function showPreview(){if(dirty&&!(await save()))return;setPreviewKey(Date.now());setPreview(true);}
  async function importContent(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>2*1024*1024)throw new Error('La copia supera 2 MB.');const value=JSON.parse(await file.text()),issues=validateContent(value);if(issues.length)throw new Error(issues.join(' '));setData(value);setMessage('Copia importada al editor. Revisa el borrador antes de aplicarlo.');setErrors([]);}catch(error){setErrors([error.message]);}}
  const exportContent=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='renovacion-63-contenido.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  if(loadError)return <main className="cms-load-state"><Icon name="info-circle"/><h1>No pudimos abrir el editor</h1><p>{loadError}</p><button className="cms-button primary" onClick={load}>Volver a intentar</button><a href="/">Ver página</a></main>;
  if(!data)return <main className="cms-load-state" aria-busy="true"><div className="cms-skeleton"/><p>Cargando tu contenido…</p></main>;
  return <div className={`cms-shell ${preview?'with-preview':''}`}><header className="cms-header"><a href="/admin/" className="cms-brand"><strong>{data.brand.number}</strong><span>{data.brand.name}<small>Editor del sitio · Local</small></span></a><button className="cms-menu-button" aria-label={menu?'Cerrar secciones':'Abrir secciones'} aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name={menu?'close':'menu'}/></button><div className="cms-header-actions"><span className={`save-indicator ${dirty?'dirty':''}`}><span/>{busy?'Guardando…':dirty?'Sin guardar':'Guardado'}</span><button className="cms-button secondary preview-button" disabled={busy} onClick={showPreview}><Icon name="eye"/>Vista previa</button><button className="cms-button secondary" disabled={busy} onClick={()=>save()}><Icon name="save"/><span>Guardar borrador</span></button><button className="cms-button primary" disabled={busy} onClick={()=>save(true)}><Icon name="check"/><span>Aplicar al sitio local</span></button></div></header>
  <aside className={`cms-sidebar ${menu?'is-open':''}`} aria-label="Secciones del editor"><nav>{tabs.map(([id,label,icon])=><button key={id} className={id===tab?'selected':''} aria-current={id===tab?'page':undefined} onClick={()=>selectTab(id)}><Icon name={icon}/>{label}</button>)}</nav><div className="cms-sidebar-bottom"><a className="cms-button quiet" href="/" target="_blank" rel="noopener"><Icon name="arrow-up-right"/>Ver sitio local</a><button className="cms-button quiet" onClick={exportContent}><Icon name="document"/>Exportar copia</button><button className="cms-button quiet" onClick={()=>importRef.current.click()}><Icon name="upload"/>Importar copia</button><input ref={importRef} type="file" accept=".json" className="upload-input" onChange={importContent}/><button className="cms-button quiet" onClick={()=>setDiscard(!discard)}><Icon name="refresh"/>Recargar contenido guardado</button>{discard&&<div className="discard-confirm"><p>Esto descarta los cambios sin guardar en el editor.</p><button className="cms-button secondary" onClick={load}>Recargar</button><button className="cms-button quiet" onClick={()=>setDiscard(false)}>Conservar cambios</button></div>}</div></aside>
  <main className="cms-editor"><div className={`cms-message ${errors.length?'has-error':''}`} role={errors.length?'alert':'status'} aria-live="polite">{message&&<p>{message}</p>}{errors.length>0&&<ul>{errors.map((error,index)=><li key={index}>{error}</li>)}</ul>}</div><fieldset className="cms-editor-fields" disabled={busy}><Editor tab={tab} data={data} update={update} csrf={state.csrfToken} setTab={selectTab}/></fieldset><div className="cms-editor-end"><Icon name="info-circle"/><p>Guardar un borrador permite revisarlo. «Aplicar al sitio local» actualiza la página de este equipo; no publica en internet.</p></div></main>
  {preview&&<aside className="cms-preview"><div><h2>Vista previa del borrador</h2><button aria-label="Cerrar vista previa" onClick={()=>setPreview(false)}><Icon name="close"/></button></div><iframe key={previewKey} src={`/?editor-preview=1&v=${previewKey}`} title="Vista previa del borrador de Renovación 63"/><a href="/?editor-preview=1" target="_blank" rel="noopener">Abrir borrador en otra pestaña <Icon name="arrow-up-right"/></a></aside>}
  </div>;
}
createRoot(document.getElementById('cms-root')).render(<CMS/>);
